### ISSUE TITLE
How to estimate the weight of the joint exposure effect when we use `qgcomp.boot` .

### ISSUE THREAD

**Issue by LeungJun24** [alexpkeil1/qgcomp#18]
Whe we use `qgcomp.boot` with bootstrapping method. How to estimate the weigths of joint exposure effect. Is it similar to 'qgcomp.noboot' to allow further to calculate the exposure weights?
![360截图20210513223823567](https://user-images.githubusercontent.com/65936988/118143893-6925f780-b43e-11eb-970e-c2f49afbd274.jpg)

**Comment by alexpkeil1** [comment]
This is not implemented in the package. The reason for this is that qgcomp.noboot will generally be useful when there is a non-linear/non-additive element to the model. In such cases, the weights are not well defined because they will be different at different levels of exposure. In your example (because you have a linear/additive model), you can get the weights by just fitting the same model using the qgcomp.noboot function. This will be correct because the weights will be based on the same underlying model in both approaches, when the underlying model is linear and addtive.
