### ISSUE TITLE
How to remove the intercept?

### ISSUE THREAD

**Issue by cbulka** [alexpkeil1/qgcomp#19]
Hello, I am wondering if there's a way to remove the intercept when using the qgcomp.boot function? I've tried adding a zero or -1 to the model formula, which works when using the R function 'glm,' but I still see an intercept term present in the model results.

**Comment by alexpkeil1** [comment]
This would be a nice feature since you may be able to reduce your variance if you know the intercept is zero!

It's not currently permitted in the R package due to how it's coded. It's not trivial to implement a general way to code this, but in the mean time, you can implement a "noboot" version of this by following the example here: https://gist.github.com/alexpkeil1/ff169e6933de2bd2f302f1fd6423e74e

The "boot" version hasn't been coded up, but I'll take a look and see if I can do something similar.

There are a few new functions that are in that file, as well as some code with a simple simulation at the bottom of the file. This won't work for using the default plotting functions, but it should be enough to get you going on analysis.

I'll put this on my to-do list for implementing in the package itself.

**Comment by alexpkeil1** [comment]
OK, the example at https://gist.github.com/alexpkeil1/ff169e6933de2bd2f302f1fd6423e74e 
now includes a "boot" example. 

For the boot version, you'll have to explicitly exclude the intercept via including -1 in the formula, or you get incorrect results. For the noboot version, if you don't exclude the intercept then the approach will still estimate an intercept, but not report it.

It turned out to be straightforward to code a one-off version of this function, but it probably won't be implemented in the package for a few months due to the need for testing and making sure that error checking catches some of the above issues.

**Comment by cbulka** [comment]
Thank you so much!!

**Comment by alexpkeil1** [comment]
Issue is resolved in v2.8.0, which was just uploaded to CRAN. Intercepts can be removed by including "-1" in the R formula using the standard qgcomp.noboot and qgcomp.boot functions

Until this version populates the CRAN mirrors, the dev version can be installed from github in R via qgcomp:::.devinstall()
