### ISSUE TITLE
Extract the exposure index

### ISSUE THREAD

**Issue by kevinluolk** [alexpkeil1/qgcomp#38]
Hi Alex, 
Thanks for working on this fabulous package enabling the assessment of the effect of the exposure mixture. I am wondering if there is a way to extract the exposure index from the fit object? Such index should be useful for downstream analyses, such as mutually adjustment for multiple groups of exposure mixture, just in the similar way of group WQS. 

Thanks. 

Kai

**Comment by alexpkeil1** [comment]
Yes. It is the “qx” part of the fitted object, e.g.

Ft = qgcomp.glm.noboot(y ~ z + x1 + x2, expnms = c('x1', 'x2'), data=dat, q=4, family=gaussian())
Ft$qx



From: Kai(kevin) Luo ***@***.***>
Date: Wednesday, July 24, 2024 at 12:06 AM
To: alexpkeil1/qgcomp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexpkeil1/qgcomp] Extract the exposure index (Issue #38)

Hi Alex,
Thanks for working on this fabulous package enabling the assessment of the effect of the exposure mixture. I am wondering if there is a way to extract the exposure index from the fit object? Such index should be useful for downstream analyses, such as mutually adjustment for multiple groups of exposure mixture, just in the similar way of group WQS.

Thanks.

Kai

**Comment by alexpkeil1** [comment]
But this isn’t really the “index” in the same way that WQS has an index. Qgcomp is able to estimate the effect of an index without actually needing to calculate it. Qgcomp.boot objects fit a marginal structural model, which uses an index, but it’s not an index calculated for the original data, so it can’t be used the way you are asking for.

From: Alexander Keil ***@***.***>
Date: Wednesday, July 24, 2024 at 9:04 AM
To: alexpkeil1/qgcomp ***@***.***>
Subject: Re: [alexpkeil1/qgcomp] Extract the exposure index (Issue #38)
Yes. It is the “qx” part of the fitted object, e.g.

Ft = qgcomp.glm.noboot(y ~ z + x1 + x2, expnms = c('x1', 'x2'), data=dat, q=4, family=gaussian())
Ft$qx



From: Kai(kevin) Luo ***@***.***>
Date: Wednesday, July 24, 2024 at 12:06 AM
To: alexpkeil1/qgcomp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexpkeil1/qgcomp] Extract the exposure index (Issue #38)

Hi Alex,
Thanks for working on this fabulous package enabling the assessment of the effect of the exposure mixture. I am wondering if there is a way to extract the exposure index from the fit object? Such index should be useful for downstream analyses, such as mutually adjustment for multiple groups of exposure mixture, just in the similar way of group WQS.

Thanks.

Kai

**Comment by kevinluolk** [comment]
> Ft$qx

Hi Alex, thanks for your prompt reply. I am aware of the qx matrix, but what I want is the mixture index, just like the sum of weighted qx. I did some simple tests to get such mixture exposure index by summing the qx matrix with the corresponding weights (negative and positive) and reran the regular regression analysis with this mixture exposure index. But the results I got were not the same as those from qgcomp.noboot fun.  I'm unsure if my manual calculation of the mixture exposure index is correct.  Any suggestions on this?  
Thanks. 

Kai

**Comment by kevinluolk** [comment]
Ok, I got your point. But it opens another question on how to assess the "exposure effect" for multiple groups of exposures within the framewok of qgcomp.

**Comment by alexpkeil1** [comment]
See my other response. Qgcomp won’t give you what you are looking for because the underlying machinery doesn’t work involve estimating a latent exposure in the way that WQS does. If you want to use multiple mixtures because you think they confound the effects of each other, you would just adjust for the exposures of the other mixture in the qgcomp model. Provided that it converges, it would be expected to be less biased than an approach that operates using explicitly estimated indexes, but the variance would be higher (so there is a bias-variance tradeoff and not likely to be a single approach that always works better). The relevant part of the vignette would be the section on partial effects, which effectively does that kind of analysis.

From: Kai(kevin) Luo ***@***.***>
Date: Wednesday, July 24, 2024 at 9:12 AM
To: alexpkeil1/qgcomp ***@***.***>
Cc: Alex Keil ***@***.***>, Comment ***@***.***>
Subject: Re: [alexpkeil1/qgcomp] Extract the exposure index (Issue #38)

Ft$qx

Hi Alex, thanks for your prompt reply. I am aware of the qx matrix, but what I want is the mixture index, just like the sum of weighted qx. I did some simple tests to get such mixture exposure index by summing the qx matrix with the corresponding weights (negative and positive) and reran the regular regression analysis with this mixture exposure index. But the results I got were not the same as those from qgcomp.noboot fun. I'm unsure if my manual calculation of the mixture exposure index is correct. Any suggestions on this?
Thanks.

Kai
