### ISSUE TITLE
Plots of qgcomp.cox.boot

### ISSUE THREAD

**Issue by ShiHongjing** [alexpkeil1/qgcomp#42]
I'm using qgcomp.cox.boot to fit a non-linear model, e.g. bs(x1) + bs(x2) + bs(x3), dgree = 3. After running it, I want to make similar plots (below) as I've seen before in the literature, but I noticed that there's no analogue to the qgcomp.glm.boot's
pointwisebound() like this can fit the mean difference corresponding to different quantile sets. Qgcomp.cox.boot can only make survival curves, but I want plots where the hazard ratio changes with quantile. Do you have any good suggestions please?
<img width="719" alt="1" src="https://github.com/user-attachments/assets/b35bb094-d649-4dc4-a2dd-d58088ea817a">

**Comment by alexpkeil1** [comment]
The survival curves are the equivalent of pointwisebound for the Cox model because it works on model predictions rather than the effect estimates. The "modelbound" functions are more like what you are looking for.

There are no convenience functions for the Cox model this in the package, so you would have to do the plot manually. The regression line is straightforward because the hazard ratio is a cubic polynomial.  If you need confidence intervals, then you would need to pull the covariance matrix and use formulae for the variance of a linear combination of random variables (see https://statproofbook.github.io/P/var-lincomb.html). Something like the code below might work

```
library(qgcomp)
set.seed(50)
N=200
dat <- data.frame(time=(tmg <- pmin(.1,rweibull(N, 10, 0.1))), 
                  d=1.0*(tmg<0.1), x1=runif(N), x2=runif(N), z=runif(N))
expnms=paste0("x", 1:2)
f = survival::Surv(time, d)~x1^2 + x2^2
(obj <- qgcomp.cox.boot(f, degree=2, expnms = expnms, data = dat, B=10, MCsize=20000))

q = c(0:3)
q2 = q^2
psicoef = obj$psi


psicov = obj$covmat.psi

lnhrvar = numeric(length(lnhr))

for(j in 1:length(q)){
  grad = c(q[j], q2[j])
  lnhrvar[j]= grad %*% psicov %*% grad
}
# log hazard ratio
lnhr= cbind(q,q2) %*% psicoef

# variance of the log hazard ratio (ref: all exposures = 0)
lnhrvar
```
